# E2E test pipeline - performs end-to-end tests on baremetal devices
# Devices must be provisioned with azure-pipelines-agent
# TODO: Add README.md

name: $(Date:yyyyMMdd)$(Rev:rr)

variables:
  SERVICE_CONNECTION: OSconfig-arm
  IOTHUBOWNER_CONN_STR: $(IOTHUBOWNER_CONNECTION_STRING)

stages:
- template: stages/e2etest_baremetal.yaml
  parameters:
    device_id: ahbenmes-rpi4-buster
    packagePattern: '**/*focal_aarch64.deb'
    environment: rpi4-arm64