# E2E test pipeline - Performs end-to-end tests
# Pipeline supports both Cloud and Baremetal targets
# Baremetal targets must be provisioned with azure-pipelines-agent (see TODO)
# TODO: Add README.md

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Date:yyyyMMdd)$(Rev:rr)

resources:
  containers:
  - container: ubuntu
    image: ubuntu:18.04
  - container: dotnet
    image: mcr.microsoft.com/dotnet/sdk:5.0

parameters:
- name: runCloudTests
  displayName: Run Cloud tests
  type: boolean
  default: true
- name: runBaremetalTests
  displayName: Run Baremetal tests
  type: boolean
  default: true
- name: testExpression
  displayName: Test expression to use
  type: string
  default: ' '
- name: skipTeardown
  displayName: Leave test infrastructure in-place
  type: boolean
  default: false
- name: packageBranch
  displayName: 'Branch to use package from (default: source branch if empty)'
  type: string
  default: ' '
- name: twinTimeout
  displayName: Timeout for twin updates
  type: number
  default: 90
# - name: PRE_SCRIPT
#   displayName: 'Shell script to execute before osconfig install'
#   type: string
#   default: ' '
- name: postScript
  displayName: Shell script to execute after osconfig install
  type: string
  default: ' '

variables:
  SERVICE_CONNECTION: OSconfig-arm
  IOTHUBOWNER_CONN_STR: $(IOTHUBOWNER_CONNECTION_STRING)

stages:
- ${{ if eq(parameters.runCloudTests, 'true') }}:
  - template: stages/e2etest_cloud.yaml
    parameters:
      testExpression: ${{ parameters.testExpression }}
      skipTeardown: ${{ parameters.skipTeardown }}
      twinTimeout: ${{ parameters.twinTimeout }}
      postScript: ${{ parameters.postScript }}
      packageBranch: ${{ parameters.packageBranch }}

- ${{ if eq(parameters.runBaremetalTests, 'true') }}:
  - template: stages/e2etest_baremetal.yaml
    parameters:
      jobName: rpi4_buster
      deviceId: ahbenmes-rpi4-buster
      packagePattern: '**/*focal_aarch64.deb'
      environment: rpi4-arm64
      testExpression: ${{ parameters.testExpression }}

  - template: stages/e2etest_baremetal.yaml
    parameters:
      jobName: nvidia_jetson_bionic
      deviceId: nvidia-jetson-arm64
      packagePattern: '**/*bionic_aarch64.deb'
      environment: nvidia-jetson-arm64
      testExpression: ${{ parameters.testExpression }}